server:
  port: 9002

spring:
  profiles:
    active: dev
  application:
    name: jcloud-provider-admin
  security:
    user:
      name: root
      password: root
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:0.0.1-SNAPSHOT

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

mybatis-plus:
  global-config:
    db-config:
      #表名前缀
      table-prefix: sys_
  configuration:
    #是否开启自动驼峰命名规则,字段aId会变成a_id
    map-underscore-to-camel-case: true

