server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  security:
    user:
      name: root
      password: root
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:@pom.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #表名前缀
      table-prefix: sys_
  configuration:
    #是否开启自动驼峰命名规则,字段aId会变成a_id
    map-underscore-to-camel-case: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-prefix: mybatis-plus

#设置打印日志
debug: true

logging:
  level:
    com.angelj.jcloudauth: DEBUG
    org.springframework.security: DEBUG