spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: jcloud-config
        enabled: true
      name: jcloud-gateway
      profile: dev
      username: root
      password: root