server:
  port: 8900

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  security:
    user:
      name: root
      password: root

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:@pom.version@
