server:
  port: 9411

spring:
  profiles:
    active: dev
  application:
    name: jcloud-zipkin
#  security:
#    user:
#      name: root
#      password: root
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:0.0.1-SNAPSHOT

management:
  metrics:
    web:
      server:
        auto-time-requests: false
