server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: jcloud-monitor
  security:
    user:
      name: root
      password: root

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:0.0.1-SNAPSHOT

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS